sudo: required
services:
- docker
before_install:
- curl -sLo- http://get.bpkg.sh | sudo bash
before_script:
- sudo bpkg install rylnd/shpec
script:
- make test
- make package
- ls -alh nodejs-npm-buildpack-*.tgz
deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  file:
    - "nodejs-npm-buildpack-${TRAVIS_TAG}.tgz"
  skip_cleanup: true
  on:
    tags: true
dist: xenial
