sudo: required
services:
  - docker
script:
  - make test
  - make package
  - ls -alh nodejs-npm-buildpack-*.tgz
deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  file:
    - "nodejs-npm-buildpack-${TRAVIS_TAG}.tgz"
  skip_cleanup: true
  on:
    tags: true
dist: xenial